name: Install_node
description:  this action is made for install some info related to node.
inputs: 
  node-version:
    description: Node.js version
    required: true
    default: "20"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with: 
       node-version: ${{ inputs.node-version }}
    - run: node --version
      shell: bash
    - run: |
        node --version
        npm --version
        echo "Node successfully installed"
      shell: bash
    - run: echo "Everything work well now."
      shell: bash
