name: Github_output_check
on:
  workflow_dispatch: 

jobs:
  Producer:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate.outputs.version }}
      # this will give me empty output version
    steps:
     - name: Generate_output
       id: generate
       run: |
        VERSION=2.0.4
        echo "version=$VERSION" >> $GITHUB_OUTPUT
     -  name: Varify
        run: |
          echo "Version inside Producer:"
          echo "${{ steps.generate.outputs.version }}"
          # this will generate the same version 
  Consumer:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.Read.outputs.version }}
    steps:
     - name: Read output
       id : Read
       run: |
        Version=2.1.4
        echo "version=$Version" >> $GITHUB_OUTPUT
     - name: Verify
       run: |
         echo "${{ steps.Read.outputs.version }}"
  anotherConsumer:
      runs-on: ubuntu-latest
      needs: 
      - Producer
      - Consumer
      steps:
       - name: Read both Versions
         run: |
          echo "This is the version of Job1 ${{ needs.Producer.outputs.version }}"
          echo "This is the version of job2 ${{ needs.Consumer.outputs.version }}"
