name: Check_permissions
on:
  workflow_dispatch:
  
    
jobs:
  demo:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Force_failure
        run: exit 1
      - name:  Will never run
        run: echo "Hello after failure"
        
