name: Flask_build
on:
  push:
    branches:
      - main
jobs:
  Frontend:
    runs-on: ubuntu-latest
    container:
     image: python:3.12
    steps:
     -  uses: actions/checkout@v4
     - run: |
        python --version
        pip --version


          
