name: Path Filter Lab

on:
  push:
    paths:
      - "docs/**"
      - "!docs/**/*.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Workflow triggered!"
      - run: echo "Changed file matched the path filter."