name: Test_reusable_workflow

on:
  workflow_dispatch:

jobs:
  Test1:
    name: invoke reusable workflow with Relative path

    uses: ./.github/workflows/reusable3.yml

    with:
      foo: bar
      environment: staging

    secrets: inherit

  Test2:
    name: invoke reusable workflow with repo + commit

    uses: your-username/your-repo/.github/workflows/reusable3.yml@main

    with:
      foo: bar
      environment: production

    secrets:
      Api_secrets: ${{ secrets.Api_secrets }}
