name: Check_reusable_workflow
on:
  workflow_call:
    inputs:
      Project_name:
        required: true
        type: string
jobs:
  Test: 
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Testing ${{ inputs.Project_name }}"
         echo "Linting..."
         echo "Running testing..."
         echo "Building..."

  
